server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dnd?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    # url: jdbc:mysql://localhost:3307/dnd?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PW}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3600
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SERVICE_ID}
    password: ${EMAIL_SERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000 # 30 * 60 * 1000 == 30?
  cache:
    type: redis
    redis:
      time-to-live: 3600
      cache-null-values: false
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        default_batch_fetch_size: 1000
  sql:
    init:
      encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  token:
    secret: ${JWT_SECRET_KEY}
